[project]
name = "blast"
description = "BLAST user interface"
version = "0.11"
authors = [
    {name = "JB", email = "j.bishop@utoronto.ca"}
]
license = {file = "LICENSE.md"}
dependencies = [
            "scipy",
            "scikit-learn",
            "numpy",
            "scikit-image",
            "SimpleITK",
            "pandas",
            "matplotlib",
            "connected-components-3d",
            "twisted",
            "versioneer"      ]
[project.urls]
"Source" = "https://github.com/jeb2112/blast"

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.
[tool.setuptools]

[build-system]
# build-backend = "flit_core.buildapi"
# requires = ["flit_core > 3.2,<4"]

# to continue using setup.py and setup.cfg
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project.scripts]
runblastui = "src.startGui:main"